### ISSUE TITLE
can't get the tweet from some tweet id

### ISSUE THREAD

**Issue by Thornhill-GYL** [kglandt/stance-detection-in-covid-19-tweets#1]
Due to permissions and other reasons, there are no relevant tweets that can be found from many tweet ids。
How to deal with it?

**Comment by kglandt** [comment]
Is this due to the tweet being deleted?

**Comment by Thornhill-GYL** [comment]
Some have been deleted, some are due to restricted viewing conditions

**Comment by kglandt** [comment]
Sorry for the delay due to personal holiday, but please send me an email and I'd be more than happy to help you.

**Comment by kglandt** [comment]
I am going to mark this as closed. If anyone else is having issues with this please reach out to me via the email listed in the paper and I will be more than happy to help you.
