### ISSUE TITLE
content field in the data set

### ISSUE THREAD

**Issue by zoujiaying1995** [kglandt/stance-detection-in-covid-19-tweets#3]
Excuse me, is there no content field in the data set (ie the original text of tweet)? I cannot find this field. Only tweetID field 。

**Comment by zoujiaying1995** [comment]
I'm sorry I didn't see the issue that you closed before. However, I also cannot get the corresponding tweets from the Twitter API due to permissions and other reasons. I wonder if you can provide me with the data set containing the tweet content fields? thanks for your help. Best Wishes.

**Comment by kglandt** [comment]
Please send me an email and I'll try to help you as best as I can.
